apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-mock-data
  labels:
    app.kubernetes.io/name: create-mock-data
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: OpenShift
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: create-mock-data
  template:
    metadata:
      labels:
        app.kubernetes.io/name: create-mock-data
    spec:
      serviceAccountName: netsentinel-sa
      containers:
        - name: create-mock-data
          image: quay.io/bpandey/netsentinel:0.0.1-services
          command: ["sh", "-c", "python create_mock_data.py"]
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 0
          env:
            - name: KAFKA_USERNAME
              value: "netsentinel-kafka-user"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netsentinel-kafka-user
                  key: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "console-kafka-kafka-secure-bootstrap:9093"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: app-config
        - name: console-kafka-cluster-ca-cert
          secret:
            secretName: console-kafka-cluster-ca-cert
