apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeek
  labels:
    app: zeek
spec:
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      serviceAccountName: zeek-privileged
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: zeek
          image: quay.io/bpandey/netsentinel-zeek:base
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: zeek-config
              mountPath: /usr/local/zeek/share/zeek/site/local.zeek
              subPath: local.zeek
            - name: zeek-config
              mountPath: /usr/local/zeek/etc/node.cfg
              subPath: node.cfg
            - name: console-kafka-cluster-ca-cert
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true
          env:
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zeek-client
                  key: password
            - name: LD_LIBRARY_PATH
              value: "/usr/local/lib"
          command: ["/usr/local/zeek/start-zeek.sh"]
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep zeek || exit 1
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pgrep zeek
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: zeek-config
          configMap:
            name: zeek-config
        - name: zeek-scripts
          emptyDir: {}
        - name: zeek-logs
          emptyDir: {}
        - name: console-kafka-cluster-ca-cert
          secret:
            secretName: console-kafka-cluster-ca-cert

# cat /usr/local/share/ca-certificates/ca.crt
# openssl s_client -connect console-kafka-kafka-secure-bootstrap:9093 -CAfile /usr/local/share/ca-certificates/ca.crt
