apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: zeek-client
  labels:
    strimzi.io/cluster: console-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: netsentinel-zeek-logs
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: netsentinel-zeek-logs
          patternType: literal
        operation: Write
      - resource:
          type: group
          name: zeek-group
          patternType: literal
        operation: Read
