apiVersion: v1
kind: Secret
metadata:
  name: console-ui-secrets
  namespace: my-project
type: Opaque
data:
  SESSION_SECRET: LW4gRjZpY01oK080VHJuT0VDaVZ3MjJjUGQ0UkJ1aFdtUEFmUG84NHZqY3JoZz0K
  NEXTAUTH_SECRET: LW4gNmIwMWpsQU9kV0p3SUNacHdxdTN4ektBVkNsOGpCUFUxYXpsTmQxVElGVT0K
