apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./console
  - ./kafka
  - ./prometheus
  - kafka-topic-processed.yaml
  - kafka-topic-raw.yaml
  - netsentinel-kafka-user.kafkauser.yaml


# Copy patches folder and apply following from your overlays
# patchesStrategicMerge:
#   - patches/console-ui.route.yaml
#   - patches/console-server.clusterrolebinding.yaml
#   - patches/console.deployment.yaml
#   - patches/console-kafka.kafka.yaml
#   - patches/console-operators.operatorgroup.yaml
#   - patches/console-prometheus-server.clusterrolebinding.yaml
